{-# OPTIONS_GHC -Wno-orphans #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE AllowAmbiguousTypes #-}

-- | Exposes an orphan instance for using overloaded labels for lenses and
-- prisms generated by `optician`. You cannot import this if the 'IsLabel'
-- instance from `Optics.Label` is in scope.
module Optician.Label
  (
  ) where

import           GHC.OverloadedLabels
import           Optics.Optic

import           Optician.Types (GenOptic, GetOpticKind, optic, SameBase, GenTypeEqualities)

-- orphan
instance ( GenOptic label s t a b
         , is ~ NoIx
         , k ~ GetOpticKind s
         , SameBase s t
         , GenTypeEqualities label s t a b
         )
  => IsLabel label (Optic k is s t a b) where
    fromLabel = optic @label
